Overhaul scripts

diff --git a/apt/templates/main/apt_check-update b/apt/templates/main/apt_check-update
--- a/apt/templates/main/apt_check-update
+++ b/apt/templates/main/apt_check-update
@@ -2,204 +2,209 @@
 
 {{ansible_managed|comment(decoration='#')}}
 
-# SHELL VARIABLES
+# Shell variables
 
 SHELL='/bin/sh'
 PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 
-# COMMANDS
+# Commands
 
-which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
-basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
-date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
-echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
-expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
-grep=$(${which} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
-hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
-logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
-{% if (apt_monitor_mail_state == True) %}
-mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
-{% endif %}
-rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-tr=$(${which} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
-touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
-wc=$(${which} wc) || { echo "Error: Command 'wc' not found."; exit 127; }
-whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
+WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
+BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
+ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
+RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
-apt_get=$(${which} apt-get) || { echo "Error: Command 'apt-get' not found."; exit 127; }
-
-# VARIABLES
-
-host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
-script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-time_start=$(${date} '+%s')
-user='{{file_owner_apt_check_update}}'
-lockfile='/var/tmp/apt_check-update.lock'
-retval=0
-severity='Debug'
-message='Please check log files for more information.'
-
-textfile_collector='{{apt_monitor_prom_textfile_collector}}'
+APT_GET=$(${WHICH} apt-get) || { echo "Error: Command 'apt-get' not found."; exit 127; }
+GREP=$(${WHICH} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
+TR=$(${WHICH} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
+WC=$(${WHICH} wc) || { echo "Error: Command 'wc' not found."; exit 127; }
 
 {% if (apt_monitor_mail_state == True) %}
-mail_from_address='{{apt_monitor_mail_from_address}}'
-mail_to_address='{% for item in apt_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
-mail_subject='apt: Check Update - Error ({{ansible_hostname}})'
+MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
 
-# FUNCTIONS
+# Environment variables
+
+HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
+SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
+TIME_START=$(${DATE} '+%s')
+USER='{{file_owner_apt_check_update}}'
+LOCKFILE='/var/tmp/apt_check-update.lock'
+TEXTFILE_COLLECTOR='{{apt_monitor_prom_textfile_collector}}'
+
+{% if (apt_monitor_mail_state == True) %}
+MAIL_FROM_ADDRESS='{{apt_monitor_mail_from_address}}'
+MAIL_TO_ADDRESS='{% for item in apt_monitor_mail_to_address%}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
+MAIL_SUBJECT='apt: Check Update - Error ({{ansible_hostname}})'
+{% endif %}
+
+# Functions
 
 {% if (apt_monitor_mail_state == True) %}
 mail_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  mail_body="ERROR
+    local exit_code=${1}
+    local message=${2}
+    local mail_body="ERROR
 
 Message     : ${message}
-Severity    : ${severity}
-Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
+Exit Code   : ${exit_code}
+Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
 
 SCRIPT
 
-Name        : apt_check-update
+Name        : ${SCRIPT_NAME}
 Type        : Shell script
-PID         : $$
+PID         : ${$}
 
 SYSTEM
 
 Hostname    : {{ansible_hostname}}
 FQDN        : {{ansible_fqdn}}"
 
-  ${echo} "${mail_body}" | ${mailx} -r "${mail_from_address}" -s "${mail_subject}" "${mail_to_address}" > /dev/null 2>&1
+    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
 }
 {% endif %}
 
 {% if (apt_monitor_prom_state == True) %}
 update_prom() {
-  retval="$1"
-  time_start="$2"
-  time_exec="$3"
+    local exit_code=${1}
+    local time_exec=${2}
 
-  if [ -w "${textfile_collector}" ]; then
-    ${echo} -e "# HELP apt_check_update_exit The script's exit code.\n"\
+    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
+        ${ECHO} -e "# HELP apt_check_update_exit The script's exit code.\n"\
 "# TYPE apt_check_update_exit counter\n"\
-"apt_check_update_exit ${retval}" > "${textfile_collector}/apt_check_update_exit.prom"
+"apt_check_update_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/apt_check_update_exit.prom"
 
-    if [ -z "${time_start}" ] ; then
-      ${rm} -f "${textfile_collector}/apt_check_update_start.prom"
-    else
-      ${echo} -e "# HELP apt_check_update_start The script's start time in epoch.\n"\
+        if [ -z "${TIME_START}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/apt_check_update_start.prom"
+        else
+            ${ECHO} -e "# HELP apt_check_update_start The script's start time in epoch.\n"\
 "# TYPE apt_check_update_start counter\n"\
-"apt_check_update_start ${time_start}" > "${textfile_collector}/apt_check_update_start.prom"
-    fi
+"apt_check_update_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/apt_check_update_start.prom"
+        fi
 
-    if [ -z "${time_exec}" ] ; then
-      ${rm} -f "${textfile_collector}/apt_check_update_duration.prom"
-    else
-      ${echo} -e "# HELP apt_check_update_duration The script's execution duration in seconds.\n"\
+        if [ -z "${time_exec}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/apt_check_update_duration.prom"
+        else
+            ${ECHO} -e "# HELP apt_check_update_duration The script's execution duration in seconds.\n"\
 "# TYPE apt_check_update_duration counter\n"\
-"apt_check_update_duration ${time_exec}" > "${textfile_collector}/apt_check_update_duration.prom"
-    fi
+"apt_check_update_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/apt_check_update_duration.prom"
+        fi
 
-    if [ -z "${packages}" ] ; then
-      ${rm} -f "${textfile_collector}/apt_check_update_packages.prom"
-    else
-      ${echo} -e "# HELP apt_check_update_packages The number of pending updates in packages.\n"\
+        if [ -z "${PACKAGES}" ] ; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/apt_check_update_packages.prom"
+        else
+            ${ECHO} -e "# HELP apt_check_update_packages The number of pending updates in packages.\n"\
 "# TYPE apt_check_update_packages counter\n"\
-"apt_check_update_packages ${packages}" > "${textfile_collector}/apt_check_update_packages.prom"
+"apt_check_update_packages ${PACKAGES}" >"${TEXTFILE_COLLECTOR}/apt_check_update_packages.prom"
+        fi
     fi
-  fi
 }
 {% endif %}
 
 check_script_user() {
-  if [ "$(${whoami})" != "${user}" ]; then
-    retval=77
-    severity='Error'
-    message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    exit "${retval}"
-  fi
+    if [ "$(${WHOAMI})" != "${USER}" ]; then
+        local exit_code=77
+        local message="Please run script as user '${USER}'"
+
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        exit ${exit_code}
+    fi
 }
 
 create_lockfile() {
-  if [ ! -e "${lockfile}" ]; then
-    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
-  fi
+    if [ ! -e "${LOCKFILE}" ]; then
+        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
+    fi
 }
 
 remove_lockfile() {
-  if [ -e "${lockfile}" ]; then
-    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
-  fi
+    if [ -e "${LOCKFILE}" ]; then
+        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
+    fi
 }
 
 log_and_exit_on_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  if [ "${retval}" -ne 0 ]; then
-    ${rm} -f "${lockfile}"
+    local exit_code=${1}
+    local message=${2}
 
-    if [ -t 1 ] ; then
-      ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    fi
+    if [ ${exit_code} -ne 0 ]; then
+        ${RM} -f ${LOCKFILE}
 
-    ${logger} -t "${script}" "${severity}: ${message}"
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        ${LOGGER} -t ${SCRIPT} "${message}"
 
 {% if (apt_monitor_mail_state == True) %}
-    mail_error "${retval}" "${severity}" "${message}"
+        mail_error ${exit_code} "${message}"
 {% endif %}
 
 {% if (apt_monitor_prom_state == True) %}
-    update_prom "${retval}" "${time_start}" "${time_exec}"
+        update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-    exit "${retval}"
-  fi
+        exit ${exit_code}
+    fi
 }
 
 log_and_exit() {
-  retval="$1"
-  severity="$2"
-  message="$3"
+    local time_end=$(${DATE} '+%s')
+    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
+    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local exit_code=${1}
+    local message=${2}
 
-  time_end=$(${date} '+%s')
-  time_exec=$(${expr} "${time_end}" - "${time_start}")
-  time_hr=$(${date} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    if [ -t 1 ]; then
+        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
+    fi
 
-  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"
 
 {% if (apt_monitor_prom_state == True) %}
-  update_prom "${retval}" "${time_start}" "${time_exec}"
+    update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-  exit "${retval}"
+    exit ${exit_code}
 }
 
-# SCRIPT
+resync_package_index() {
+    ${APT_GET} --quiet update >/dev/null 2>&1
+    log_and_exit_on_error "${?}" 'Error' 'Unable to resynchronize package index files.'
+}
 
-check_script_user
+get_pending_updates() {
+    PACKAGES=$(${APT_GET} --quiet --simulate dist-upgrade | ${GREP} '^Inst ' | ${WC} -l)
+    log_and_exit_on_error "${?}" 'Error' 'Unable to check for updates.'
+}
 
-create_lockfile
+# Establish run order
+main() {
+    check_script_user
+    create_lockfile
+    resync_package_index
+    get_pending_updates
+    remove_lockfile
+    if [ "${PACKAGES}" -ne 0 ]; then
+        log_and_exit '100' "System has pending updates (${PACKAGES})."
+    else
+        log_and_exit '0' 'System is up-to-date.'
+    fi
+}
 
-# Resynchronize package index files
-${apt_get} --quiet update > /dev/null 2>&1
-log_and_exit_on_error "$?" 'Error' 'Unable to resynchronize package index files.'
-
-# Check for pending updates
-packages=$(${apt_get} --quiet --simulate dist-upgrade | ${grep} '^Inst ' | ${wc} -l)
-log_and_exit_on_error "$?" 'Error' 'Unable to check for updates.'
-
-remove_lockfile
-
-if [ "${packages}" -ne 0 ]; then
-  log_and_exit '100' 'Warn' "System has pending updates (${packages})."
-else
-  log_and_exit '0' 'Info' 'System is up-to-date.'
-fi
+main
diff --git a/chrony/templates/main/chrony_update-time b/chrony/templates/main/chrony_update-time
--- a/chrony/templates/main/chrony_update-time
+++ b/chrony/templates/main/chrony_update-time
@@ -2,193 +2,198 @@
 
 {{ansible_managed|comment(decoration='#')}}
 
-# SHELL VARIABLES
+# Shell variables
 
 SHELL='/bin/sh'
 PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 
-# COMMANDS
+# Commands
 
-which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
-basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
-date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
-echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
-expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
-hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
-logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
-{% if (chrony_monitor_mail_state == True) %}
-mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
-{% endif %}
-rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
-whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
+WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
+BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
+ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
+RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
-chronyd='{{chronyd}}'
-
-# VARIABLES
-
-host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
-script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-time_start=$(${date} '+%s')
-user='{{file_owner_chrony_update_time}}'
-lockfile='/var/tmp/chrony_update-time.lock'
-retval=0
-severity='Debug'
-message='Please check log files for more information.'
-
-chrony_servers='{% for item in chrony_server %}{{item.address}}{% if not loop.last %} {% endif %}{% endfor %}'
-textfile_collector='{{chrony_monitor_prom_textfile_collector}}'
+CHRONYD='{{chronyd}}'
 
 {% if (chrony_monitor_mail_state == True) %}
-mail_from_address='{{chrony_monitor_mail_from_address}}'
-mail_to_address='{% for item in chrony_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
-mail_subject='chrony: Update Time - Error ({{ansible_hostname}})'
+MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
 
-# FUNCTIONS
+# Environment variables
+
+HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
+SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
+TIME_START=$(${DATE} '+%s')
+USER='{{file_owner_chrony_update_time}}'
+LOCKFILE='/var/tmp/chrony_update-time.lock'
+TEXTFILE_COLLECTOR='{{chrony_monitor_prom_textfile_collector}}'
+
+CHRONY_SERVERS='{% for item in chrony_server %}{{item.address}}{% if not loop.last %} {% endif %}{% endfor %}'
+
+{% if (chrony_monitor_mail_state == True) %}
+MAIL_FROM_ADDRESS='{{chrony_monitor_mail_from_address}}'
+MAIL_TO_ADDRESS='{% for item in chrony_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
+MAIL_SUBJECT='chrony: Update Time - Error ({{ansible_hostname}})'
+{% endif %}
+
+# Functions
 
 {% if (chrony_monitor_mail_state == True) %}
 mail_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  mail_body="ERROR
+    local exit_code=${1}
+    local message=${2}
+    local mail_body="ERROR
 
 Message     : ${message}
-Severity    : ${severity}
-Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
+Exit Code   : ${exit_code}
+Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
 
 SCRIPT
 
-Name        : chrony_update-time
+Name        : ${SCRIPT_NAME}
 Type        : Shell script
-PID         : $$
+PID         : ${$}
 
 SYSTEM
 
 Hostname    : {{ansible_hostname}}
 FQDN        : {{ansible_fqdn}}"
 
-  ${echo} "${mail_body}" | ${mailx} -r "${mail_from_address}" -s "${mail_subject}" "${mail_to_address}" > /dev/null 2>&1
+    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
 }
 {% endif %}
 
 {% if (chrony_monitor_prom_state == True) %}
 update_prom() {
-  retval="$1"
-  time_start="$2"
-  time_exec="$3"
+    local exit_code=${1}
+    local time_exec=${2}
 
-  if [ -w "${textfile_collector}" ]; then
-    ${echo} -e "# HELP chrony_update_time_exit The script's exit code.\n"\
+    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
+        ${ECHO} -e "# HELP chrony_update_time_exit The script's exit code.\n"\
 "# TYPE chrony_update_time_exit counter\n"\
-"chrony_update_time_exit ${retval}" > "${textfile_collector}/chrony_update_time_exit.prom"
+"chrony_update_time_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/chrony_update_time_exit.prom"
 
-    if [ -z "${time_start}" ] ; then
-      ${rm} -f "${textfile_collector}/chrony_update_time_start.prom"
-    else
-      ${echo} -e "# HELP chrony_update_time_start The script's start time in epoch.\n"\
+        if [ -z "${TIME_START}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/chrony_update_time_start.prom"
+        else
+            ${ECHO} -e "# HELP chrony_update_time_start The script's start time in epoch.\n"\
 "# TYPE chrony_update_time_start counter\n"\
-"chrony_update_time_start ${time_start}" > "${textfile_collector}/chrony_update_time_start.prom"
-    fi
+"chrony_update_time_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/chrony_update_time_start.prom"
+        fi
 
-    if [ -z "${time_exec}" ] ; then
-      ${rm} -f "${textfile_collector}/chrony_update_time_duration.prom"
-    else
-      ${echo} -e "# HELP chrony_update_time_duration The script's execution duration in seconds.\n"\
+        if [ -z "${time_exec}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/chrony_update_time_duration.prom"
+        else
+            ${ECHO} -e "# HELP chrony_update_time_duration The script's execution duration in seconds.\n"\
 "# TYPE chrony_update_time_duration counter\n"\
-"chrony_update_time_duration ${time_exec}" > "${textfile_collector}/chrony_update_time_duration.prom"
+"chrony_update_time_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/chrony_update_time_duration.prom"
+        fi
     fi
-  fi
 }
 {% endif %}
 
 check_script_user() {
-  if [ "$(${whoami})" != "${user}" ]; then
-    retval=77
-    severity='Error'
-    message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    exit "${retval}"
-  fi
+    if [ "$(${WHOAMI})" != "${USER}" ]; then
+        local exit_code=77
+        local message="Please run script as user '${USER}'"
+
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        exit ${exit_code}
+    fi
 }
 
 create_lockfile() {
-  if [ ! -e "${lockfile}" ]; then
-    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
-  fi
+    if [ ! -e "${LOCKFILE}" ]; then
+        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
+    fi
 }
 
 remove_lockfile() {
-  if [ -e "${lockfile}" ]; then
-    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
-  fi
+    if [ -e "${LOCKFILE}" ]; then
+        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
+    fi
 }
 
 log_and_exit_on_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  if [ "${retval}" -ne 0 ]; then
-    ${rm} -f "${lockfile}"
+    local exit_code=${1}
+    local message=${2}
 
-    if [ -t 1 ] ; then
-      ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    fi
+    if [ ${exit_code} -ne 0 ]; then
+        ${RM} -f ${LOCKFILE}
 
-    ${logger} -t "${script}" "${severity}: ${message}"
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        ${LOGGER} -t ${SCRIPT} "${message}"
 
 {% if (chrony_monitor_mail_state == True) %}
-    mail_error "${retval}" "${severity}" "${message}"
+        mail_error ${exit_code} "${message}"
 {% endif %}
 
 {% if (chrony_monitor_prom_state == True) %}
-    update_prom "${retval}" "${time_start}" "${time_exec}"
+        update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-    exit "${retval}"
-  fi
+        exit ${exit_code}
+    fi
 }
 
 log_and_exit() {
-  time_end=$(${date} '+%s')
-  time_exec=$(${expr} "${time_end}" - "${time_start}")
-  time_hr=$(${date} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local time_end=$(${DATE} '+%s')
+    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
+    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local exit_code=${1}
+    local message=${2}
 
-  retval=0
-  severity='Info'
-  message='System time and hardware clock updated.'
-  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+    if [ -t 1 ]; then
+        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
+    fi
+
+    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"
 
 {% if (chrony_monitor_prom_state == True) %}
-  update_prom "${retval}" "${time_start}" "${time_exec}"
+    update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-  exit "${retval}"
+    exit ${exit_code}
 }
 
-# SCRIPT
+update_system_time() {
+    for chrony_server in ${CHRONY_SERVERS} ; do
+        ${CHRONYD} "server ${chrony_server} iburst" >/dev/null 2>&1
+        if [ "${?}" -eq 0 ]; then
+            chrony_status=0
+            break;
+        else
+            chrony_status=1
+        fi
+    done
+    log_and_exit_on_error "${chrony_status}" 'Error' 'Unable to update the system time.'
+}
 
-check_script_user
+# Establish run order
+main() {
+    check_script_user
+    create_lockfile
+    update_system_time
+    remove_lockfile
+    log_and_exit '0' 'System time and hardware clock updated.'
+}
 
-create_lockfile
-
-# Update the system time by polling NTP servers
-for chrony_server in ${chrony_servers} ; do
-  ${chronyd} "server ${chrony_server} iburst" > /dev/null 2>&1
-  if [ "$?" -eq 0 ]; then
-    chrony_status=0
-    break;
-  else
-    chrony_status=1
-  fi
-done
-log_and_exit_on_error "${chrony_status}" 'Error' 'Unable to update the system time.'
-
-remove_lockfile
-
-log_and_exit
+main
diff --git a/mariadb/templates/main/mariadb_run-backup b/mariadb/templates/main/mariadb_run-backup
--- a/mariadb/templates/main/mariadb_run-backup
+++ b/mariadb/templates/main/mariadb_run-backup
@@ -2,235 +2,248 @@
 
 {{ansible_managed|comment(decoration='#')}}
 
-# SHELL VARIABLES
+# Shell variables
 
 SHELL='/bin/sh'
 PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 
-# COMMANDS
+# Commands
 
-which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
-basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
-chmod=$(${which} chmod) || { echo "Error: Command 'chmod' not found."; exit 127; }
-chown=$(${which} chown) || { echo "Error: Command 'chown' not found."; exit 127; }
-date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
-echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
-expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
-find=$(${which} find) || { echo "Error: Command 'find' not found."; exit 127; }
-grep=$(${which} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
-gzip=$(${which} gzip) || { echo "Error: Command 'gzip' not found."; exit 127; }
-hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
-logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
-{% if (mariadb_monitor_mail_state == True) %}
-mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
-{% endif %}
-rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-service=$(${which} service) || { echo "Error: Command 'service' not found."; exit 127; }
-tar=$(${which} tar) || { echo "Error: Command 'tar' not found."; exit 127; }
-touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
-whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
+WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
+BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
+ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
+RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
-mysql=$(${which} mysql) || { echo "Error: Command 'mysql' not found."; exit 127; }
-mysqldump=$(${which} mysqldump) || { echo "Error: Command 'mysqldump' not found."; exit 127; }
-
-# VARIABLES
-
-host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
-script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-time_start=$(${date} '+%s')
-user='{{file_owner_mariadb_run_backup}}'
-lockfile='/var/tmp/mariadb_run-backup.lock'
-retval=0
-severity='Debug'
-message='Please check log files for more information.'
-
-mariadb_service_name='{{service_name_mariadb}}'
-credentials_cnf='{{file_dst_credentials_cnf}}'
-backup_dir='{{file_dst_mariadb_backup_dir}}'
-backup_timestamp=$(${date} '+%Y%m%d-%H%M%S%z')
-backup_file_owner='{{file_owner_mariadb_backup_file}}'
-backup_file_group='{{file_group_mariadb_backup_file}}'
-backup_file_mode='{{file_mode_mariadb_backup_file}}'
-backup_exclude="{% if not (mariadb_run_backup_exclude == []) %}{% for item in mariadb_run_backup_exclude %}{{item}}{% if not loop.last %}|{% endif %}{% endfor %}{% else %} {% endif %}"
-keep_days={{(mariadb_run_backup_keep_days|int(2))}}
-textfile_collector='{{mariadb_monitor_prom_textfile_collector}}'
+CHMOD=$(${WHICH} chmod) || { echo "Error: Command 'chmod' not found."; exit 127; }
+CHOWN=$(${WHICH} chown) || { echo "Error: Command 'chown' not found."; exit 127; }
+FIND=$(${WHICH} find) || { echo "Error: Command 'find' not found."; exit 127; }
+GREP=$(${WHICH} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
+GZIP=$(${WHICH} gzip) || { echo "Error: Command 'gzip' not found."; exit 127; }
+MYSQL=$(${WHICH} mysql) || { echo "Error: Command 'mysql' not found."; exit 127; }
+MYSQLDUMP=$(${WHICH} mysqldump) || { echo "Error: Command 'mysqldump' not found."; exit 127; }
+SERVICE=$(${WHICH} service) || { echo "Error: Command 'service' not found."; exit 127; }
+TAR=$(${WHICH} tar) || { echo "Error: Command 'tar' not found."; exit 127; }
 
 {% if (mariadb_monitor_mail_state == True) %}
-mail_from_address='{{mariadb_monitor_mail_from_address}}'
-mail_to_address='{% for item in mariadb_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
-mail_subject='MariaDB: Run Backup - Error ({{ansible_hostname}})'
+MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
 
-# FUNCTIONS
+# Environment variables
+
+HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
+SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
+TIME_START=$(${DATE} '+%s')
+USER='{{file_owner_mariadb_run_backup}}'
+LOCKFILE='/var/tmp/mariadb_run-backup.lock'
+TEXTFILE_COLLECTOR='{{mariadb_monitor_prom_textfile_collector}}'
+
+MARIADB_SERVICE_NAME='{{service_name_mariadb}}'
+CREDENTIALS_CNF='{{file_dst_credentials_cnf}}'
+BACKUP_DIR='{{file_dst_mariadb_backup_dir}}'
+BACKUP_TIMESTAMP=$(${DATE} '+%Y%m%d-%H%M%S%z')
+BACKUP_FILE_OWNER='{{file_owner_mariadb_backup_file}}'
+BACKUP_FILE_GROUP='{{file_group_mariadb_backup_file}}'
+BACKUP_FILE_MODE='{{file_mode_mariadb_backup_file}}'
+BACKUP_EXCLUDE="{% if not (mariadb_run_backup_exclude == []) %}{% for item in mariadb_run_backup_exclude %}{{item}}{% if not loop.last %}|{% endif %}{% endfor %}{% else %} {% endif %}"
+KEEP_DAYS={{mariadb_run_backup_keep_days|int(2)}}
+
+{% if (mariadb_monitor_mail_state == True) %}
+MAIL_FROM_ADDRESS='{{mariadb_monitor_mail_from_address}}'
+MAIL_TO_ADDRESS='{% for item in mariadb_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
+MAIL_SUBJECT='MariaDB: Run Backup - Error ({{ansible_hostname}})'
+{% endif %}
+
+# Functions
 
 {% if (mariadb_monitor_mail_state == True) %}
 mail_error() {
-  retval="$"1
-  severity="$2"
-  message="$3"
-  mail_body="ERROR
+    local exit_code=${1}
+    local message=${2}
+    local mail_body="ERROR
 
 Message     : ${message}
-Severity    : ${severity}
-Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
+Exit Code   : ${exit_code}
+Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
 
 SCRIPT
 
-Name        : mariadb_run-backup
+Name        : ${SCRIPT_NAME}
 Type        : Shell script
-PID         : $$
+PID         : ${$}
 
 SYSTEM
 
 Hostname    : {{ansible_hostname}}
 FQDN        : {{ansible_fqdn}}"
 
-  ${echo} "${mail_body}" | ${mailx} -r "${mail_from_address}" -s "${mail_subject}" "${mail_to_address}" > /dev/null 2>&1
+    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
 }
 {% endif %}
 
 {% if (mariadb_monitor_prom_state == True) %}
 update_prom() {
-  retval="$1"
-  time_start="$2"
-  time_exec="$3"
+    local exit_code=${1}
+    local time_exec=${2}
 
-  if [ -w "${textfile_collector}" ]; then
-    ${echo} -e "# HELP mariadb_run_backup_exit The script's exit code.\n"\
+    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
+        ${ECHO} -e "# HELP mariadb_run_backup_exit The script's exit code.\n"\
 "# TYPE mariadb_run_backup_exit counter\n"\
-"mariadb_run_backup_exit ${retval}" > "${textfile_collector}/mariadb_run_backup_exit.prom"
+"mariadb_run_backup_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/mariadb_run_backup_exit.prom"
 
-    if [ -z "${time_start}" ] ; then
-      ${rm} -f "${textfile_collector}/mariadb_run_backup_start.prom"
-    else
-      ${echo} -e "# HELP mariadb_run_backup_start The script's start time in epoch.\n"\
+        if [ -z "${TIME_START}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/mariadb_run_backup_start.prom"
+        else
+            ${ECHO} -e "# HELP mariadb_run_backup_start The script's start time in epoch.\n"\
 "# TYPE mariadb_run_backup_start counter\n"\
-"mariadb_run_backup_start ${time_start}" > "${textfile_collector}/mariadb_run_backup_start.prom"
-    fi
+"mariadb_run_backup_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/mariadb_run_backup_start.prom"
+        fi
 
-    if [ -z "${time_exec}" ] ; then
-      ${rm} -f "${textfile_collector}/mariadb_run_backup_duration.prom"
-    else
-      ${echo} -e "# HELP mariadb_run_backup_duration The script's execution duration in seconds.\n"\
+        if [ -z "${time_exec}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/mariadb_run_backup_duration.prom"
+        else
+            ${ECHO} -e "# HELP mariadb_run_backup_duration The script's execution duration in seconds.\n"\
 "# TYPE mariadb_run_backup_duration counter\n"\
-"mariadb_run_backup_duration ${time_exec}" > "${textfile_collector}/mariadb_run_backup_duration.prom"
+"mariadb_run_backup_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/mariadb_run_backup_duration.prom"
+        fi
     fi
-  fi
 }
 {% endif %}
 
 check_script_user() {
-  if [ "$(${whoami})" != "${user}" ]; then
-    retval=77
-    severity='Error'
-    message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    exit "${retval}"
-  fi
+    if [ "$(${WHOAMI})" != "${USER}" ]; then
+        local exit_code=77
+        local message="Please run script as user '${USER}'"
+
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        exit ${exit_code}
+    fi
 }
 
 create_lockfile() {
-  if [ ! -e "${lockfile}" ]; then
-    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
-  fi
+    if [ ! -e "${LOCKFILE}" ]; then
+        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
+    fi
 }
 
 remove_lockfile() {
-  if [ -e "${lockfile}" ]; then
-    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
-  fi
+    if [ -e "${LOCKFILE}" ]; then
+        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
+    fi
 }
 
 log_and_exit_on_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  if [ "${retval}" -ne 0 ]; then
-    ${rm} -f "${lockfile}"
+    local exit_code=${1}
+    local message=${2}
 
-    if [ -t 1 ] ; then
-      ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    fi
+    if [ ${exit_code} -ne 0 ]; then
+        ${RM} -f ${LOCKFILE}
 
-    ${logger} -t "${script}" "${severity}: ${message}"
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        ${LOGGER} -t ${SCRIPT} "${message}"
 
 {% if (mariadb_monitor_mail_state == True) %}
-    mail_error "${retval}" "${severity}" "${message}"
+        mail_error ${exit_code} "${message}"
 {% endif %}
 
 {% if (mariadb_monitor_prom_state == True) %}
-    update_prom "${retval}" "${time_start}" "${time_exec}"
+        update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-    exit "${retval}"
-  fi
+        exit ${exit_code}
+    fi
 }
 
 log_and_exit() {
-  time_end=$(${date} '+%s')
-  time_exec=$(${expr} "${time_end}" - "${time_start}")
-  time_hr=$(${date} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local time_end=$(${DATE} '+%s')
+    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
+    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local exit_code=${1}
+    local message=${2}
 
-  retval=0
-  severity='Info'
-  message='Backup created successfully.'
-  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+    if [ -t 1 ]; then
+        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
+    fi
+
+    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"
 
 {% if (mariadb_monitor_prom_state == True) %}
-  update_prom "${retval}" "${time_start}" "${time_exec}"
+    update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-  exit "${retval}"
+    exit ${exit_code}
 }
 
-# SCRIPT
+check_mariadb_service() {
+    ${SERVICE} ${MARIADB_SERVICE_NAME} status >/dev/null 2>&1
+    log_and_exit_on_error "${?}" 'MariaDB server is not running.'
+}
 
-check_script_user
+get_mariadb_databases() {
+    DATABASES=$(${MYSQL} --defaults-file=${CREDENTIALS_CNF} --execute='show databases' --skip-column-names | ${GREP} -vE "${BACKUP_EXCLUDE}")
+    log_and_exit_on_error "${?}" 'Unable to get individual MariaDB databases.'
+}
 
-create_lockfile
+dump_and_compress_database_dumps() {
+    for db in ${DATABASES} ; do
+        ${MYSQLDUMP} --defaults-file=${CREDENTIALS_CNF} --add-drop-database --add-drop-table --allow-keywords --quote-names --single-transaction --events --routines \
+            --log-error="${BACKUP_DIR}/${db}_${BACKUP_TIMESTAMP}-error.log" "${db}" | ${GZIP} -c >"${BACKUP_DIR}/${db}_${BACKUP_TIMESTAMP}.gz"
+        if [ "${?}" -eq 0 ]; then
+            local message="'${db}' dumped and compressed."
+            ${LOGGER} -t ${SCRIPT} "${message}"
+        else
+            log_and_exit_on_error "${?}" "Unable to dump and compress '${db}'."
+        fi
 
-# Check if MariaDB server is running
-${service} ${mariadb_service_name} status > /dev/null 2>&1
-log_and_exit_on_error "$?" 'Warning' 'MariaDB server is not running.'
+        ${TAR} -C${BACKUP_DIR} -c -f"${BACKUP_DIR}/${HOST}_${db}_${BACKUP_TIMESTAMP}.tar" "${db}_${BACKUP_TIMESTAMP}-error.log" "${db}_${BACKUP_TIMESTAMP}.gz"
+        log_and_exit_on_error "${?}" "Unable to archive '${db}'."
 
-# Get individual MariaDB databases
-databases=$(${mysql} --defaults-file=${credentials_cnf} --execute='show databases' --skip-column-names | ${grep} -vE "${backup_exclude}")
-log_and_exit_on_error "$?" 'Error' 'Unable to get individual MariaDB databases.'
+        ${RM} -f "${BACKUP_DIR}/${db}_${BACKUP_TIMESTAMP}-error.log" "${BACKUP_DIR}/${db}_${BACKUP_TIMESTAMP}.gz"
+        log_and_exit_on_error "${?}" "Unable to remove unpacked '${db}'."
+    done
+}
 
-# Dump and compress individual MariaDB databases
-for db in ${databases} ; do
-  ${mysqldump} --defaults-file=${credentials_cnf} --add-drop-database --add-drop-table --allow-keywords --quote-names --single-transaction --events --routines --log-error="${backup_dir}/${db}_${backup_timestamp}-error.log" "${db}" | ${gzip} -c > "${backup_dir}/${db}_${backup_timestamp}.gz"
-  if [ "$?" -eq 0 ]; then
-    severity='Info'
-    message="'${db}' dumped and compressed."
-    ${logger} -t "${script}" "${severity}: ${message}"
-  else
-    log_and_exit_on_error "$?" 'Error' "Unable to dump and compress '${db}'."
-  fi
+update_database_dumps_permissions() {
+    ${FIND} "${BACKUP_DIR}" -type f -name "${HOST}_*_${BACKUP_TIMESTAMP}.tar" -exec ${CHOWN} ${BACKUP_FILE_OWNER}:${BACKUP_FILE_GROUP} '{}' ';'
+    log_and_exit_on_error "${?}" 'Unable to ensure proper file owner and group.'
 
-  ${tar} -C${backup_dir} -c -f"${backup_dir}/${host}_${db}_${backup_timestamp}.tar" "${db}_${backup_timestamp}-error.log" "${db}_${backup_timestamp}.gz"
-  log_and_exit_on_error "$?" 'Error' "Unable to archive '${db}'."
+    ${FIND} "${BACKUP_DIR}" -type f -name "${HOST}_*_${BACKUP_TIMESTAMP}.tar" -exec ${CHMOD} ${BACKUP_FILE_MODE} '{}' ';'
+    log_and_exit_on_error "${?}" 'Unable to ensure proper file permission.'
+}
 
-  ${rm} -f "${backup_dir}/${db}_${backup_timestamp}-error.log" "${backup_dir}/${db}_${backup_timestamp}.gz"
-  log_and_exit_on_error "$?" 'Error' "Unable to remove unpacked '${db}'."
-done
+remove_old_database_dumps() {
+    ${FIND} "${BACKUP_DIR}" -type f -name "${HOST}_*.tar" -mtime +${KEEP_DAYS} -exec ${RM} -f '{}' ';'
+    log_and_exit_on_error "${?}" 'Unable to remove old MariaDB database dumps.'
+}
 
-# Ensure proper file owner and group
-${find} "${backup_dir}" -type f -name "${host}_*_${backup_timestamp}.tar" -exec ${chown} ${backup_file_owner}:${backup_file_group} '{}' ';'
-log_and_exit_on_error "$?" 'Error' 'Unable to ensure proper file owner and group.'
+# Establish run order
+main() {
+    check_script_user
+    create_lockfile
+    check_mariadb_service
+    get_mariadb_databases
+    dump_and_compress_database_dumps
+    update_database_dumps_permissions
+    remove_old_database_dumps
+    remove_lockfile
+    log_and_exit '0' 'Backup created successfully.'
 
-# Ensure proper file permission
-${find} "${backup_dir}" -type f -name "${host}_*_${backup_timestamp}.tar" -exec ${chmod} ${backup_file_mode} '{}' ';'
-log_and_exit_on_error "$?" 'Error' 'Unable to ensure proper file permission.'
+}
 
-# Remove old MariaDB database dumps
-${find} "${backup_dir}" -type f -name "${host}_*.tar" -mtime +${keep_days} -exec ${rm} -f '{}' ';'
-log_and_exit_on_error "$?" 'Error' 'Unable to remove old MariaDB database dumps.'
-
-remove_lockfile
-
-log_and_exit
+main
diff --git a/openntpd/templates/main/openntpd_check-time b/openntpd/templates/main/openntpd_check-time
--- a/openntpd/templates/main/openntpd_check-time
+++ b/openntpd/templates/main/openntpd_check-time
@@ -2,225 +2,233 @@
 
 {{ansible_managed|comment(decoration='#')}}
 
-# SHELL VARIABLES
+# Shell variables
 
 SHELL='/bin/sh'
 PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 
-# COMMANDS
+# Commands
 
-which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
-awk=$(${which} awk) || { echo "Error: Command 'awk' not found."; exit 127; }
-basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
-date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
-echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
-expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
-grep=$(${which} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
-hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
-logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
-{% if (openntpd_monitor_mail_state == True) %}
-mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
-{% endif %}
-ntpctl=$(${which} ntpctl) || { echo "Error: Command 'ntpctl' not found."; exit 127; }
-rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-sed=$(${which} sed) || { echo "Error: Command 'sed' not found."; exit 127; }
-sleep=$(${which} sleep) || { echo "Error: Command 'sleep' not found."; exit 127; }
-touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
-whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
+WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
+BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
+ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
+RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
-# VARIABLES
-
-host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
-script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-time_start=$(${date} '+%s')
-user='{{file_owner_openntpd_check_time}}'
-lockfile='/var/tmp/openntpd_check-time.lock'
-retval=0
-severity='Debug'
-message='Please check log files for more information.'
-
-offset_limit='{{openntpd_check_time_offset_limit}}'
-textfile_collector='{{openntpd_monitor_prom_textfile_collector}}'
+AWK=$(${WHICH} awk) || { echo "Error: Command 'awk' not found."; exit 127; }
+GREP=$(${WHICH} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
+NTPCTL=$(${WHICH} ntpctl) || { echo "Error: Command 'ntpctl' not found."; exit 127; }
+SED=$(${WHICH} sed) || { echo "Error: Command 'sed' not found."; exit 127; }
+SLEEP=$(${WHICH} sleep) || { echo "Error: Command 'sleep' not found."; exit 127; }
 
 {% if (openntpd_monitor_mail_state == True) %}
-mail_from_address='{{openntpd_monitor_mail_from_address}}'
-mail_to_address='{% for item in openntpd_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
-mail_subject='openntpd: Check Time - Error ({{ansible_hostname}})'
+MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
 
-# FUNCTIONS
+# Environment variables
+
+HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
+SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
+TIME_START=$(${DATE} '+%s')
+USER='{{file_owner_openntpd_check_time}}'
+LOCKFILE='/var/tmp/openntpd_check-time.lock'
+TEXTFILE_COLLECTOR='{{openntpd_monitor_prom_textfile_collector}}'
+
+OFFSET_LIMIT='{{openntpd_check_time_offset_limit}}'
+
+{% if (openntpd_monitor_mail_state == True) %}
+MAIL_FROM_ADDRESS='{{openntpd_monitor_mail_from_address}}'
+MAIL_TO_ADDRESS='{% for item in openntpd_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
+MAIL_SUBJECT='openntpd: Check Time - Error ({{ansible_hostname}})'
+{% endif %}
+
+# Functions
 
 {% if (openntpd_monitor_mail_state == True) %}
 mail_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  mail_body="ERROR
+    local exit_code=${1}
+    local message=${2}
+    local mail_body="ERROR
 
 Message     : ${message}
-Severity    : ${severity}
-Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
+Exit Code   : ${exit_code}
+Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
 
 SCRIPT
 
-Name        : openntpd_check-time
+Name        : ${SCRIPT_NAME}
 Type        : Shell script
-PID         : $$
+PID         : ${$}
 
 SYSTEM
 
 Hostname    : {{ansible_hostname}}
 FQDN        : {{ansible_fqdn}}"
 
-  ${echo} "${mail_body}" | ${mailx} -r "${mail_from_address}" -s "${mail_subject}" "${mail_to_address}" > /dev/null 2>&1
+    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
 }
 {% endif %}
 
 {% if (openntpd_monitor_prom_state == True) %}
 update_prom() {
-  retval="$1"
-  time_start="$2"
-  time_exec="$3"
+    local exit_code=${1}
+    local time_exec=${2}
 
-  if [ -w "${textfile_collector}" ]; then
-    ${echo} "# HELP openntpd_check_time_exit The script's exit code.
-# TYPE openntpd_check_time_exit counter
-openntpd_check_time_exit ${retval}" > "${textfile_collector}/openntpd_check_time_exit.prom"
+    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
+        ${ECHO} -e "# HELP openntpd_check_time_exit The script's exit code.\n"\
+"# TYPE openntpd_check_time_exit counter\n"\
+"openntpd_check_time_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/openntpd_check_time_exit.prom"
 
-    if [ -z "${time_start}" ] ; then
-      ${rm} -f "${textfile_collector}/openntpd_check_time_start.prom"
-    else
-      ${echo} "# HELP openntpd_check_time_start The script's start time in epoch.
-# TYPE openntpd_check_time_start counter
-openntpd_check_time_start ${time_start}" > "${textfile_collector}/openntpd_check_time_start.prom"
-    fi
+        if [ -z "${TIME_START}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/openntpd_check_time_start.prom"
+        else
+            ${ECHO} -e "# HELP openntpd_check_time_start The script's start time in epoch.\n"\
+"# TYPE openntpd_check_time_start counter\n"\
+"openntpd_check_time_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/openntpd_check_time_start.prom"
+        fi
 
-    if [ -z "${time_exec}" ] ; then
-      ${rm} -f "${textfile_collector}/openntpd_check_time_duration.prom"
-    else
-      ${echo} "# HELP openntpd_check_time_duration The script's execution duration in seconds.
-# TYPE openntpd_check_time_duration counter
-openntpd_check_time_duration ${time_exec}" > "${textfile_collector}/openntpd_check_time_duration.prom"
-    fi
+        if [ -z "${time_exec}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/openntpd_check_time_duration.prom"
+        else
+            ${ECHO} -e "# HELP openntpd_check_time_duration The script's execution duration in seconds.\n"\
+"# TYPE openntpd_check_time_duration counter\n"\
+"openntpd_check_time_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/openntpd_check_time_duration.prom"
+        fi
 
-    if [ -z "${offset_raw}" ] ; then
-      ${rm} -f "${textfile_collector}/openntpd_check_time_offset.prom"
-    else
-      ${echo} "# HELP openntpd_check_time_offset The system time offset in milliseconds.
+        if [ -z "${OFFSET_RAW}" ] ; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/openntpd_check_time_offset.prom"
+        else
+            ${ECHO} "# HELP openntpd_check_time_offset The system time offset in milliseconds.
 # TYPE openntpd_check_time_offset counter
-openntpd_check_time_offset{limit=\"${offset_limit}\"} ${offset_raw}" > "${textfile_collector}/openntpd_check_time_offset.prom"
+openntpd_check_time_offset{limit=\"${OFFSET_LIMIT}\"} ${OFFSET_RAW}" >"${TEXTFILE_COLLECTOR}/openntpd_check_time_offset.prom"
+        fi
     fi
-  fi
 }
 {% endif %}
 
 check_script_user() {
-  if [ "$(${whoami})" != "${user}" ]; then
-    retval=77
-    severity='Error'
-    message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    exit "${retval}"
-  fi
+    if [ "$(${WHOAMI})" != "${USER}" ]; then
+        local exit_code=77
+        local message="Please run script as user '${USER}'"
+
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        exit ${exit_code}
+    fi
 }
 
 create_lockfile() {
-  if [ ! -e "${lockfile}" ]; then
-    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
-  fi
+    if [ ! -e "${LOCKFILE}" ]; then
+        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
+    fi
 }
 
 remove_lockfile() {
-  if [ -e "${lockfile}" ]; then
-    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
-  fi
+    if [ -e "${LOCKFILE}" ]; then
+        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
+    fi
 }
 
 log_and_exit_on_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  if [ "${retval}" -ne 0 ]; then
-    ${rm} -f "${lockfile}"
-    if [ -t 1 ] ; then
-      ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    fi
-    ${logger} -t "${script}" "${severity}: ${message}"
+    local exit_code=${1}
+    local message=${2}
+
+    if [ ${exit_code} -ne 0 ]; then
+        ${RM} -f ${LOCKFILE}
+
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        ${LOGGER} -t ${SCRIPT} "${message}"
+
 {% if (openntpd_monitor_mail_state == True) %}
-    mail_error "${retval}" "${severity}" "${message}"
+        mail_error ${exit_code} "${message}"
 {% endif %}
 
 {% if (openntpd_monitor_prom_state == True) %}
-    update_prom "${retval}" "${time_start}" "${time_exec}"
+        update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-    exit "${retval}"
-  fi
+        exit ${exit_code}
+    fi
 }
 
 log_and_exit() {
-  time_end=$(${date} '+%s')
-  time_exec=$(${expr} "${time_end}" - "${time_start}")
-  time_hr=$(${date} -u -r "${time_exec}" '+%H:%M:%S')
+    local time_end=$(${DATE} '+%s')
+    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
+    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local exit_code=${1}
+    local message=${2}
 
-  retval=0
-  severity='Info'
-  message='System time is synchronized.'
-  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+    if [ -t 1 ]; then
+        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
+    fi
+
+    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"
 
 {% if (openntpd_monitor_prom_state == True) %}
-  update_prom "${retval}" "${time_start}" "${time_exec}"
+    update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-  exit "${retval}"
+    exit ${exit_code}
 }
 
-watch_and_wait_for_change() {
-  watch_key="$1"
-  watch_value="$2"
-  watch_option="$3"
-  time_step="$4"
-  time_maximum="$5"
-  while ${watch_key} | ${grep} ${watch_option} "${watch_value}" > /dev/null 2>&1 ; do
-    log_and_exit_on_error "$?" 'Error' 'Unable to get system time status.'
-    if [ "${time_initial}" -lt "${time_maximum}" ]; then
-      time_initial=$(${expr} "${time_initial}" + "${time_step}")
-      ${sleep} "${time_initial}"
-    else
-    log_and_exit_on_error "1" 'Error' 'System time is not synchronized.'
+get_system_time_status() {
+    local time_initial=0
+
+    # Wait while 'unsynchronised'
+    while ${NTPCTL} -s status | ${GREP} 'unsynced' >/dev/null 2>&1 ; do
+        log_and_exit_on_error "${?}" 'Unable to get system time status.'
+        if [ "${time_initial}" -lt 32 ]; then
+            time_initial=$(${EXPR} "${time_initial}" + 2)
+            ${SLEEP} "${time_initial}"
+        else
+            log_and_exit_on_error '1' 'System time is not synchronized.'
+        fi
+    done
+}
+
+get_system_time_offset() {
+    OFFSET_RAW=$(${NTPCTL} -s peers | ${AWK} '/^ \*/ {gsub(/ms/,"");print $7}')
+    log_and_exit_on_error "${?}" 'Unable to get system time offset.'
+}
+
+convert_system_time_offset() {
+    OFFSET=$(${ECHO} "${OFFSET_RAW}" | ${SED} -n 's@\([-0-9]*\).*@\1@p' | ${SED} 's@[-]@@g')
+    log_and_exit_on_error "${?}" 'Unable to convert system time offset.'
+}
+
+check_system_time_offset() {
+    if [ -z "${OFFSET}" ] ; then
+        log_and_exit_on_error '1' 'System time is not synchronized with any peer.'
+    elif [ "${OFFSET}" -ge "${OFFSET_LIMIT}" ]; then
+        log_and_exit_on_error '1' "System time offset limit exceeded (${OFFSET}/${OFFSET_LIMIT} ms)."
     fi
-  done
 }
 
-# SCRIPT
+# Establish run order
+main() {
+    check_script_user
+    create_lockfile
+    get_system_time_status
+    get_system_time_offset
+    convert_system_time_offset
+    check_system_time_offset
+    remove_lockfile
+    log_and_exit '0' 'System time is synchronized.'
+}
 
-check_script_user
-
-create_lockfile
-
-# Get system time status and wait while 'unsynced'
-time_initial=0
-watch_and_wait_for_change "${ntpctl} -s status" 'unsynced' '' '2' '32'
-
-# Get system time offset
-offset_raw=$(${ntpctl} -s peers | ${awk} '/^ \*/ {gsub(/ms/,"");print $7}')
-log_and_exit_on_error "$?" 'Error' 'Unable to get system time offset.'
-
-# Convert system time offset
-offset=$(${echo} "${offset_raw}" | ${sed} -n 's@\([-0-9]*\).*@\1@p' | ${sed} 's@[-]@@g')
-log_and_exit_on_error "$?" 'Error' 'Unable to convert system time offset.'
-
-# Check system time offset
-if [ -z "${offset}" ] ; then
-  log_and_exit_on_error '1' 'Error' 'System time is not synchronized with any peer.'
-elif [ "${offset}" -ge "${offset_limit}" ]; then
-  log_and_exit_on_error '1' 'Error' "System time offset limit exceeded (${offset}/${offset_limit} ms)."
-fi
-
-remove_lockfile
-
-log_and_exit
+main
diff --git a/zfs/templates/main/zfs_check-pools b/zfs/templates/main/zfs_check-pools
--- a/zfs/templates/main/zfs_check-pools
+++ b/zfs/templates/main/zfs_check-pools
@@ -2,194 +2,198 @@
 
 {{ansible_managed|comment(decoration='#')}}
 
-# SHELL VARIABLES
+# Shell variables
 
 SHELL='/bin/sh'
 PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 
-# COMMANDS
+# Commands
 
-which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
-awk=$(${which} awk) || { echo "Error: Command 'awk' not found."; exit 127; }
-basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
-date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
-echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
-expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
-grep=$(${which} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
-hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
-logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
-{% if (zfs_monitor_mail_state == True) %}
-mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
-{% endif %}
-rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-sleep=$(${which} sleep) || { echo "Error: Command 'sleep' not found."; exit 127; }
-touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
-whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
+WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
+BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
+ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
+RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
-zpool=$(${which} zpool) || { echo "Error: Command 'zpool' not found."; exit 127; }
-
-# VARIABLES
-
-host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
-script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-time_start=$(${date} '+%s')
-user='{{file_owner_zfs_check_pools}}'
-lockfile='/var/tmp/zfs_check-pools.lock'
-retval=0
-severity='Debug'
-message='Please check log files for more information.'
-
-textfile_collector='{{zfs_monitor_prom_textfile_collector}}'
+AWK=$(${WHICH} awk) || { echo "Error: Command 'awk' not found."; exit 127; }
+GREP=$(${WHICH} grep) || { echo "Error: Command 'grep' not found."; exit 127; }
+SLEEP=$(${WHICH} sleep) || { echo "Error: Command 'sleep' not found."; exit 127; }
+ZPOOL=$(${WHICH} zpool) || { echo "Error: Command 'zpool' not found."; exit 127; }
 
 {% if (zfs_monitor_mail_state == True) %}
-mail_from_address='{{zfs_monitor_mail_from_address}}'
-mail_to_address='{% for item in zfs_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
-mail_subject='zfs: Check Pool - Error ({{ansible_hostname}})'
+MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
 
-# FUNCTIONS
+# Environment variables
+
+HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
+SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
+TIME_START=$(${DATE} '+%s')
+USER='{{file_owner_zfs_check_pools}}'
+LOCKFILE='/var/tmp/zfs_check-pools.lock'
+TEXTFILE_COLLECTOR='{{zfs_monitor_prom_textfile_collector}}'
+
+{% if (zfs_monitor_mail_state == True) %}
+MAIL_FROM_ADDRESS='{{zfs_monitor_mail_from_address}}'
+MAIL_TO_ADDRESS='{% for item in zfs_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
+MAIL_SUBJECT='zfs: Check Pool - Error ({{ansible_hostname}})'
+{% endif %}
+
+# Functions
 
 {% if (zfs_monitor_mail_state == True) %}
 mail_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  mail_body="ERROR
+    local exit_code=${1}
+    local message=${2}
+    local mail_body="ERROR
 
 Message     : ${message}
-Severity    : ${severity}
-Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
+Exit Code   : ${exit_code}
+Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
 
 SCRIPT
 
-Name        : zfs_check-pools
+Name        : ${SCRIPT_NAME}
 Type        : Shell script
-PID         : $$
+PID         : ${$}
 
 SYSTEM
 
 Hostname    : {{ansible_hostname}}
 FQDN        : {{ansible_fqdn}}"
 
-  ${echo} "${mail_body}" | ${mailx} -r "${mail_from_address}" -s "${mail_subject}" "${mail_to_address}" > /dev/null 2>&1
+    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
 }
 {% endif %}
 
 {% if (zfs_monitor_prom_state == True) %}
 update_prom() {
-  retval="$1"
-  time_start="$2"
-  time_exec="$3"
+    local exit_code=${1}
+    local time_exec=${2}
 
-  if [ -w "${textfile_collector}" ]; then
-    ${echo} -e "# HELP zfs_check_pools_exit The script's exit code.\n"\
+    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
+        ${ECHO} -e "# HELP zfs_check_pools_exit The script's exit code.\n"\
 "# TYPE zfs_check_pools_exit counter\n"\
-"zfs_check_pools_exit ${retval}" > "${textfile_collector}/zfs_check_pools_exit.prom"
+"zfs_check_pools_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/zfs_check_pools_exit.prom"
 
-    if [ -z "${time_start}" ] ; then
-      ${rm} -f "${textfile_collector}/zfs_check_pools_start.prom"
-    else
-      ${echo} -e "# HELP zfs_check_pools_start The script's start time in epoch.\n"\
+        if [ -z "${TIME_START}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/zfs_check_pools_start.prom"
+        else
+            ${ECHO} -e "# HELP zfs_check_pools_start The script's start time in epoch.\n"\
 "# TYPE zfs_check_pools_start counter\n"\
-"zfs_check_pools_start ${time_start}" > "${textfile_collector}/zfs_check_pools_start.prom"
-    fi
+"zfs_check_pools_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/zfs_check_pools_start.prom"
+        fi
 
-    if [ -z "${time_exec}" ] ; then
-      ${rm} -f "${textfile_collector}/zfs_check_pools_duration.prom"
-    else
-      ${echo} -e "# HELP zfs_check_pools_duration The script's execution duration in seconds.\n"\
+        if [ -z "${time_exec}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/zfs_check_pools_duration.prom"
+        else
+            ${ECHO} -e "# HELP zfs_check_pools_duration The script's execution duration in seconds.\n"\
 "# TYPE zfs_check_pools_duration counter\n"\
-"zfs_check_pools_duration ${time_exec}" > "${textfile_collector}/zfs_check_pools_duration.prom"
+"zfs_check_pools_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/zfs_check_pools_duration.prom"
+        fi
     fi
-  fi
 }
 {% endif %}
 
 check_script_user() {
-  if [ "$(${whoami})" != "${user}" ]; then
-    retval=77
-    severity='Error'
-    message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    exit "${retval}"
-  fi
+    if [ "$(${WHOAMI})" != "${USER}" ]; then
+        local exit_code=77
+        local message="Please run script as user '${USER}'"
+
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        exit ${exit_code}
+    fi
 }
 
 create_lockfile() {
-  if [ ! -e "${lockfile}" ]; then
-    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
-  fi
+    if [ ! -e "${LOCKFILE}" ]; then
+        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
+    fi
 }
 
 remove_lockfile() {
-  if [ -e "${lockfile}" ]; then
-    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
-  fi
+    if [ -e "${LOCKFILE}" ]; then
+        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
+    fi
 }
 
 log_and_exit_on_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  if [ "${retval}" -ne 0 ]; then
-    ${rm} -f "${lockfile}"
+    local exit_code=${1}
+    local message=${2}
 
-    if [ -t 1 ] ; then
-      ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    fi
+    if [ ${exit_code} -ne 0 ]; then
+        ${RM} -f ${LOCKFILE}
 
-    ${logger} -t "${script}" "${severity}: ${message}"
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        ${LOGGER} -t ${SCRIPT} "${message}"
 
 {% if (zfs_monitor_mail_state == True) %}
-    mail_error "${retval}" "${severity}" "${message}"
+        mail_error ${exit_code} "${message}"
 {% endif %}
 
 {% if (zfs_monitor_prom_state == True) %}
-    update_prom "${retval}" "${time_start}" "${time_exec}"
+        update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-    exit "${retval}"
-  fi
+        exit ${exit_code}
+    fi
 }
 
 log_and_exit() {
-  time_end=$(${date} '+%s')
-  time_exec=$(${expr} "${time_end}" - "${time_start}")
-  time_hr=$(${date} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local time_end=$(${DATE} '+%s')
+    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
+    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local exit_code=${1}
+    local message=${2}
 
-  retval=0
-  severity='Info'
-  message='All ZFS pools are healthy.'
-  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+    if [ -t 1 ]; then
+        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
+    fi
+
+    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"
 
 {% if (zfs_monitor_prom_state == True) %}
-  update_prom "${retval}" "${time_start}" "${time_exec}"
+    update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-  exit "${retval}"
+    exit ${exit_code}
 }
 
-# SCRIPT
+check_zfs_pools() {
+    for pool in $(${ZPOOL} list | ${AWK} '!/NAME/{print $1}') ; do
+        # Get ZFS pool status
+        local zfs_pool_status="$(${ZPOOL} status -xv ${POOL})"
+        log_and_exit_on_error "${?}" "Unable to get ZFS pool status: '${pool}'"
 
-check_script_user
+        # Check ZFS pool status
+        ${ECHO} "${zfs_pool_status}" | ${GREP} 'healthy' >/dev/null 2>&1
+        log_and_exit_on_error "${?}" "ZFS pool is unhealthy: '${pool}'"
+    done
+}
 
-create_lockfile
+# Establish run order
+main() {
+    check_script_user
+    create_lockfile
+    check_zfs_pools
+    remove_lockfile
+    log_and_exit '0' 'All ZFS pools are healthy.'
+}
 
-# Check ZFS pools
-for pool in $(${zpool} list | ${awk} '!/NAME/{print $1}') ; do
-  # Get ZFS pool status
-  zfs_pool_status="$(${zpool} status -xv ${pool})"
-  log_and_exit_on_error "$?" 'Error' "Unable to get ZFS pool status: '${pool}'"
-
-  # Check ZFS pool status
-  echo "${zfs_pool_status}" | ${grep} 'healthy' > /dev/null 2>&1
-  log_and_exit_on_error "$?" 'Critical' "ZFS pool is unhealthy: '${pool}'"
-done
-
-remove_lockfile
-
-log_and_exit
+main
