fstrim: - Overhaul script

diff --git a/fstrim/templates/main/fstrim_discard-blocks b/fstrim/templates/main/fstrim_discard-blocks
--- a/fstrim/templates/main/fstrim_discard-blocks
+++ b/fstrim/templates/main/fstrim_discard-blocks
@@ -2,198 +2,200 @@
 
 {{ansible_managed|comment(decoration='#')}}
 
-# SHELL VARIABLES
+# Shell variables
 
 SHELL='/bin/sh'
 PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 
-# COMMANDS
+# Commands
 
-which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
-basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
-date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
-echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
-expr=$(${which} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
-hostname=$(${which} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
-logger=$(${which} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
+WHICH='/usr/bin/which' && [ -x ${WHICH} ] || { echo "Error: Command 'which' not found."; exit 127; }
+BASENAME=$(${WHICH} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
+DATE=$(${WHICH} date) || { echo "Error: Command 'date' not found."; exit 127; }
+ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
+EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
+HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
+LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
 {% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
-mailx=$(${which} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
+MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
 {% endif %}
-rm=$(${which} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-tr=$(${which} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
-touch=$(${which} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
-whoami=$(${which} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
+RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
+TR=$(${WHICH} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
+TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
+WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
-fstrim=$(${which} fstrim) || { echo "Error: Command 'fstrim' not found."; exit 127; }
+FSTRIM=$(${WHICH} fstrim) || { echo "Error: Command 'fstrim' not found."; exit 127; }
 
-# VARIABLES
+# Environment variables
 
-host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
-script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
-time_start=$(${date} '+%s')
-user='{{file_owner_fstrim_discard_blocks}}'
-lockfile='/var/tmp/fstrim_discard-blocks.lock'
-retval=0
-severity='Debug'
-message='Please check log files for more information.'
-
-log_file='{{file_dst_fstrim_log}}'
-textfile_collector='{{fstrim_monitor_prom_textfile_collector}}'
+HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
+SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+TIME_START=$(${DATE} '+%s')
+USER='{{file_owner_fstrim_discard_blocks}}'
+LOCKFILE='/var/tmp/fstrim_discard-blocks.lock'
+LOG_FILE='{{file_dst_fstrim_log}}'
+TEXTFILE_COLLECTOR='{{fstrim_monitor_prom_textfile_collector}}'
 
 {% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
-mail_from_address='{{fstrim_monitor_mail_from_address}}'
-mail_to_address='{% for item in fstrim_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
-mail_subject='fstrim: Discard Blocks - Error ({{ansible_hostname}})'
+MAIL_FROM_ADDRESS='{{fstrim_monitor_mail_from_address}}'
+MAIL_TO_ADDRESS='{% for item in fstrim_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
+MAIL_SUBJECT='fstrim: Discard Blocks - Error ({{ansible_hostname}})'
 {% endif %}
 
-# FUNCTIONS
+# Functions
 
 {% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
 mail_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  mail_body="ERROR
+    exit_code=${1}
+    message=${2}
+    mail_body="ERROR
 
 Message     : ${message}
-Severity    : ${severity}
-Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
+Exit Code   : ${exit_code}
+Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
 
 SCRIPT
 
 Name        : fstrim_discard-blocks
 Type        : Shell script
-PID         : $$
+PID         : ${$}
 
 SYSTEM
 
 Hostname    : {{ansible_hostname}}
 FQDN        : {{ansible_fqdn}}"
 
-  ${echo} "${mail_body}" | ${mailx} -r "${mail_from_address}" -s "${mail_subject}" "${mail_to_address}" > /dev/null 2>&1
+    ${ECHO} "${mail_body}" | ${MAILX} -r "${MAIL_FROM_ADDRESS}" -s "${MAIL_SUBJECT}" "${MAIL_TO_ADDRESS}" >/dev/null 2>&1
 }
 {% endif %}
 
 {% if (fstrim_monitor_prom_state is match('true|yes|enable')) %}
 update_prom() {
-  retval="$1"
-  time_start="$2"
-  time_exec="$3"
+    local exit_code=${1}
+    local time_exec=${2}
 
-  if [ -w "${textfile_collector}" ]; then
-    ${echo} -e "# HELP fstrim_discard_blocks_exit The script's exit code.\n"\
+    if [ -w "${TEXTFILE_COLLECTOR}" ]; then
+        if [ -z "${exit_code}" ]; then
+            ${ECHO} -e "# HELP fstrim_discard_blocks_exit The script's exit code.\n"\
 "# TYPE fstrim_discard_blocks_exit counter\n"\
-"fstrim_discard_blocks_exit ${retval}" > "${textfile_collector}/fstrim_discard_blocks_exit.prom"
+"fstrim_discard_blocks_exit ${exit_code}" >"${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_exit.prom"
+        fi
 
-    if [ -z "${time_start}" ] ; then
-      ${rm} -f "${textfile_collector}/fstrim_discard_blocks_start.prom"
-    else
-      ${echo} -e "# HELP fstrim_discard_blocks_start The script's start time in epoch.\n"\
+        if [ -z "${TIME_START}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_start.prom"
+        else
+            ${ECHO} -e "# HELP fstrim_discard_blocks_start The script's start time in epoch.\n"\
 "# TYPE fstrim_discard_blocks_start counter\n"\
-"fstrim_discard_blocks_start ${time_start}" > "${textfile_collector}/fstrim_discard_blocks_start.prom"
-    fi
+"fstrim_discard_blocks_start ${TIME_START}" >"${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_start.prom"
+        fi
 
-    if [ -z "${time_exec}" ] ; then
-      ${rm} -f "${textfile_collector}/fstrim_discard_blocks_duration.prom"
-    else
-      ${echo} -e "# HELP fstrim_discard_blocks_duration The script's execution duration in seconds.\n"\
+        if [ -z "${time_exec}" ]; then
+            ${RM} -f "${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_duration.prom"
+        else
+            ${ECHO} -e "# HELP fstrim_discard_blocks_duration The script's execution duration in seconds.\n"\
 "# TYPE fstrim_discard_blocks_duration counter\n"\
-"fstrim_discard_blocks_duration ${time_exec}" > "${textfile_collector}/fstrim_discard_blocks_duration.prom"
+"fstrim_discard_blocks_duration ${time_exec}" >"${TEXTFILE_COLLECTOR}/fstrim_discard_blocks_duration.prom"
+        fi
     fi
-  fi
 }
 {% endif %}
 
 check_script_user() {
-  if [ "$(${whoami})" != "${user}" ]; then
-    retval=77
-    severity='Error'
-    message="Please run script as user '${user}'"
-    ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    exit "${retval}"
-  fi
+    if [ "$(${WHOAMI})" != "${USER}" ]; then
+        local exit_code=77
+        local message="Please run script as user '${USER}'"
+
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
+
+        exit ${exit_code}
+    fi
 }
 
 create_lockfile() {
-  if [ ! -e "${lockfile}" ]; then
-    ${touch} "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not create lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile does already exist. Please investigate.'
-  fi
+    if [ ! -e "${LOCKFILE}" ]; then
+        ${TOUCH} ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not create lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile does already exist. Please investigate.'
+    fi
 }
 
 remove_lockfile() {
-  if [ -e "${lockfile}" ]; then
-    ${rm} -f "${lockfile}" || log_and_exit_on_error "$?" 'Warning' 'Could not remove lockfile. Please investigate.'
-  else
-    log_and_exit_on_error "$?" 'Warning' 'Lockfile did not exist. Please investigate.'
-  fi
+    if [ -e "${LOCKFILE}" ]; then
+        ${RM} -f ${LOCKFILE} || log_and_exit_on_error "${?}" 'Could not remove lockfile. Please investigate.'
+    else
+        log_and_exit_on_error "${?}" 'Lockfile did not exist. Please investigate.'
+    fi
 }
 
 log_and_exit_on_error() {
-  retval="$1"
-  severity="$2"
-  message="$3"
-  if [ "${retval}" -ne 0 ]; then
-    ${rm} -f "${lockfile}"
+    local exit_code=${1}
+    local message=${2}
+    if [ ${exit_code} -ne 0 ]; then
+        ${RM} -f ${LOCKFILE}
 
-    if [ -t 1 ] ; then
-      ${echo} "$(${date} '+%Y-%m-%dT%H:%M:%S%z') - ${host} - ${script}: ${severity}: ${message}"
-    fi
+        if [ -t 1 ]; then
+            ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}" >&2
+        fi
 
-    ${logger} -t "${script}" "${severity}: ${message}"
+        ${LOGGER} -t ${SCRIPT} "${message}"
 
 {% if (fstrim_monitor_mail_state is match('true|yes|enable')) %}
-    mail_error "${retval}" "${severity}" "${message}"
+        mail_error ${exit_code} "${message}"
 {% endif %}
 
 {% if (fstrim_monitor_prom_state is match('true|yes|enable')) %}
-    update_prom "${retval}" "${time_start}" "${time_exec}"
+        update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-    add_log_header 'fstrim failed'
+        add_log_header 'fstrim failed'
 
-    exit "${retval}"
-  fi
+        exit ${exit_code}
+    fi
 }
 
 log_and_exit() {
-  time_end=$(${date} '+%s')
-  time_exec=$(${expr} "${time_end}" - "${time_start}")
-  time_hr=$(${date} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
-  retval=0
-  severity='Info'
-  message='Unused blocks discarded successfully.'
-  ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
+    local time_end=$(${DATE} '+%s')
+    local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
+    local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
+    local exit_code=0
+    local message='Unused blocks discarded successfully.'
+
+    if [ -t 1 ]; then
+        ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
+    fi
+
+    ${LOGGER} -t ${SCRIPT} "${message} Duration: ${time_hr}"
 
 {% if (fstrim_monitor_prom_state is match('true|yes|enable')) %}
-  update_prom "${retval}" "${time_start}" "${time_exec}"
+    update_prom "${exit_code}" "${time_exec}"
 {% endif %}
 
-  exit "${retval}"
+    exit ${exit_code}
 }
 
 add_log_header() {
-  name="$1"
-  name_upper=$(${echo} "${name}" | ${tr} '[:lower:]' '[:upper:]')
-  date_time=$(${date} '+%Y-%m-%dT%H:%M:%S%z')
-  echo "# ${name_upper} | ${date_time}" >> ${log_file}
+    local name=${1}
+    local name_upper=$(${ECHO} ${name} | ${TR} '[:lower:]' '[:upper:]')
+    local date_time=$(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
+    echo "# ${name_upper} | ${date_time}" >>${LOG_FILE}
 }
 
-# SCRIPT
+discard_unused_blocks() {
+    ${FSTRIM} --all --verbose >>${LOG_FILE} 2>&1
+    log_and_exit_on_error "${?}" 'Unable to discard unused blocks.'
+}
 
-check_script_user
+# Establish run order
+main() {
+    check_script_user
+    create_lockfile
+    add_log_header 'fstrim started'
+    discard_unused_blocks
+    add_log_header 'fstrim successful'
+    remove_lockfile
+    log_and_exit
+}
 
-create_lockfile
-
-add_log_header 'fstrim started'
-
-# Discard unused blocks
-${fstrim} --all --verbose >> ${log_file} 2>&1
-log_and_exit_on_error "$?" 'Error' 'Unable to discard unused blocks.'
-
-add_log_header 'fstrim successful'
-
-remove_lockfile
-
-log_and_exit
+main
