Minor script improvements

diff --git a/fstrim/templates/main/fstrim_discard-blocks b/fstrim/templates/main/fstrim_discard-blocks
--- a/fstrim/templates/main/fstrim_discard-blocks
+++ b/fstrim/templates/main/fstrim_discard-blocks
@@ -16,25 +16,28 @@ ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
 EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
 HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
 LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
-{% if (fstrim_monitor_mail_state == True) %}
-MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
-{% endif %}
 RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-TR=$(${WHICH} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
 TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
 WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
 FSTRIM=$(${WHICH} fstrim) || { echo "Error: Command 'fstrim' not found."; exit 127; }
+TR=$(${WHICH} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
+
+{% if (fstrim_monitor_mail_state == True) %}
+MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
+{% endif %}
 
 # Environment variables
 
 HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
 SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
 TIME_START=$(${DATE} '+%s')
 USER='{{file_owner_fstrim_discard_blocks}}'
 LOCKFILE='/var/tmp/fstrim_discard-blocks.lock'
-LOG_FILE='{{file_dst_fstrim_log}}'
 TEXTFILE_COLLECTOR='{{fstrim_monitor_prom_textfile_collector}}'
+
+LOG_FILE='{{file_dst_fstrim_log}}'
 
 {% if (fstrim_monitor_mail_state == True) %}
 MAIL_FROM_ADDRESS='{{fstrim_monitor_mail_from_address}}'
@@ -46,9 +49,9 @@ MAIL_SUBJECT='fstrim: Discard Blocks - Error ({{ansible_hostname}})'
 
 {% if (fstrim_monitor_mail_state == True) %}
 mail_error() {
-    exit_code=${1}
-    message=${2}
-    mail_body="ERROR
+    local exit_code=${1}
+    local message=${2}
+    local mail_body="ERROR
 
 Message     : ${message}
 Exit Code   : ${exit_code}
@@ -56,7 +59,7 @@ Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
 
 SCRIPT
 
-Name        : fstrim_discard-blocks
+Name        : ${SCRIPT_NAME}
 Type        : Shell script
 PID         : ${$}
 
@@ -130,6 +133,7 @@ remove_lockfile() {
 log_and_exit_on_error() {
     local exit_code=${1}
     local message=${2}
+
     if [ ${exit_code} -ne 0 ]; then
         ${RM} -f ${LOCKFILE}
 
@@ -157,8 +161,8 @@ log_and_exit() {
     local time_end=$(${DATE} '+%s')
     local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
     local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
-    local exit_code=0
-    local message='Unused blocks discarded successfully.'
+    local exit_code=${1}
+    local message=${2}
 
     if [ -t 1 ]; then
         ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
@@ -193,7 +197,7 @@ main() {
     discard_unused_blocks
     add_log_header 'fstrim successful'
     remove_lockfile
-    log_and_exit
+    log_and_exit '0' 'Unused blocks discarded successfully.'
 }
 
 main
diff --git a/restic/templates/main/restic_run-backup b/restic/templates/main/restic_run-backup
--- a/restic/templates/main/restic_run-backup
+++ b/restic/templates/main/restic_run-backup
@@ -16,20 +16,22 @@ ECHO=$(${WHICH} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
 EXPR=$(${WHICH} expr) || { echo "Error: Command 'expr' not found."; exit 127; }
 HOSTNAME=$(${WHICH} hostname) || { echo "Error: Command 'hostname' not found."; exit 127; }
 LOGGER=$(${WHICH} logger) || { echo "Error: Command 'logger' not found."; exit 127; }
-{% if (restic_monitor_mail_state == True) %}
-MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
-{% endif %}
 RM=$(${WHICH} rm) || { echo "Error: Command 'rm' not found."; exit 127; }
-TR=$(${WHICH} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
 TOUCH=$(${WHICH} touch) || { echo "Error: Command 'touch' not found."; exit 127; }
 WHOAMI=$(${WHICH} whoami) || { echo "Error: Command 'whoami' not found."; exit 127; }
 
 RESTIC='{{file_dst_restic}}' && [ -x ${RESTIC} ] || { echo "Error: Command 'restic' not found."; exit 127; }
+TR=$(${WHICH} tr) || { echo "Error: Command 'tr' not found."; exit 127; }
+
+{% if (restic_monitor_mail_state == True) %}
+MAILX=$(${WHICH} mailx) || { echo "Error: Command 'mailx' not found."; exit 127; }
+{% endif %}
 
 # Environment variables
 
 HOST=$(${HOSTNAME} -s) || { echo "Error: Host name unknown."; exit 68; }
 SCRIPT="$(${BASENAME} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
+SCRIPT_NAME="$(${BASENAME} $0)" || { echo "Error: Command invoked cannot execute."; exit 126; }
 TIME_START=$(${DATE} '+%s')
 USER='{{file_owner_restic_run_backup}}'
 LOCKFILE='/var/tmp/restic_run-backup.lock'
@@ -76,7 +78,7 @@ Date & Time : $(${DATE} '+%Y-%m-%dT%H:%M:%S%z')
 
 SCRIPT
 
-Name        : restic_run-backup
+Name        : ${SCRIPT_NAME}
 Type        : Shell script
 PID         : ${$}
 
@@ -177,8 +179,8 @@ log_and_exit() {
     local time_end=$(${DATE} '+%s')
     local time_exec=$(${EXPR} ${time_end} - ${TIME_START})
     local time_hr=$(${DATE} -d "1970-01-01 ${time_exec} sec" '+%H:%M:%S')
-    local exit_code=0
-    local message='Backup created successfully.'
+    local exit_code=${1}
+    local message=${2}
 
     if [ -t 1 ]; then
         ${ECHO} "$(${DATE} '+%Y-%m-%dT%H:%M:%S%z') - ${HOST} - ${SCRIPT}: ${message}"
@@ -253,7 +255,7 @@ main() {
     check_backup_repository
     add_log_header 'backup successful'
     remove_lockfile
-    log_and_exit
+    log_and_exit '0' 'Backup created successfully.'
 }
 
 main
